// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Badge: typeof import('./components/Badge.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    PageHeader: typeof import('./components/Admin/PageHeader.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    Sidebar: typeof import('./components/Admin/Sidebar.vue')['default']
    Table: typeof import('./components/Table.vue')['default']
  }
}
